## 1 . 创建二维数组

In [2]:
import numpy as np

list2 = [[1, 2], [3, 4], [5, 6]]
list2

[[1, 2], [3, 4], [5, 6]]

## 2 . 创建一个数组并改变它

In [3]:
list_1 = np.arange(24)
print(type(list_1))
list_1.shape = (2, 3, 4)
list_1

<class 'numpy.ndarray'>


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

## 3 . 改变数组形状

In [4]:
a_other = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
print(a_other)
#变成一个三行四列的数组
a_other_new = a_other.reshape(3, 4)
print(a_other_new)
#变成两个两行三列的数组
a_other1 = a_other.reshape((2, 2, 3))
a_other1

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [5]:
four_other = np.array([[1, 2, 3], [4, 5, 6]])
five = four_other.reshape((6,))
five

array([1, 2, 3, 4, 5, 6])

## 4 . 截取数组中的行列

In [6]:
a1 = np.arange(24)
a1.shape = (4, 6)
a1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [7]:
print(a1[[3], [2]])

[20]


In [8]:
#取不连续的多列
#  冒号指所有行，0，2，3分别指第一、三、四列
print(a1[:, [0, 2, 3]])

[[ 0  2  3]
 [ 6  8  9]
 [12 14 15]
 [18 20 21]]


In [9]:
#截取第1、3、4行
print(a1[[0, 2, 3]])
#截取第1，3，4行的所有列
print(a1[[0, 2, 3], :])
#截取第第1行第1列，第2行第2列，第2行第4列的元素
print(a1[[0, 1, 1], [0, 1, 3]])

[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[0 7 9]


## 4.1数组中的数值修改

In [10]:
a2 = a1
#修改第二行的值
a2[1, :] = 8
a2
#使用逻辑运算
a2[(a2 > 1) & (a2 < 9)] = 0  #与

In [11]:
a2[(a2 < 2) | (a2 > 19)] = 8  #或
a2

array([[ 8,  8,  8,  8,  8,  8],
       [ 8,  8,  8,  8,  8,  8],
       [12, 13, 14, 15, 16, 17],
       [18, 19,  8,  8,  8,  8]])

In [12]:
print(a2)
a2[~(a2 > 8)] = 5  #非


[[ 8  8  8  8  8  8]
 [ 8  8  8  8  8  8]
 [12 13 14 15 16 17]
 [18 19  8  8  8  8]]


## 5 . 数组中的轴

In [13]:
import numpy as np

a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
print(np.sum(a, axis=1))  #所有行之和
print(np.sum(a, axis=0))

[ 6 15]
[5 7 9]


In [15]:
a_1 = np.arange(27).reshape((3, 3, 3))
a_1

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [16]:
b = np.sum(a_1, axis=0)
print(b)
print('*' * 20)
c = np.sum(a_1, axis=1)
print(c)
print('*' * 20)
c = np.sum(a_1, axis=2)
print(c)

[[27 30 33]
 [36 39 42]
 [45 48 51]]
********************
[[ 9 12 15]
 [36 39 42]
 [63 66 69]]
********************
[[ 3 12 21]
 [30 39 48]
 [57 66 75]]


## 6、数组与数组的计算

In [17]:
t1 = np.arange(24).reshape((6, 4))
print(t1)
print(t1 / 2)  #数组中所有的元素除以二

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0.   0.5  1.   1.5]
 [ 2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5]]


In [18]:
print(t1 * 2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]


In [19]:
print(t1 + 2)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]


In [20]:
t2 = np.arange(100, 124).reshape(6, 4)
t2

array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111],
       [112, 113, 114, 115],
       [116, 117, 118, 119],
       [120, 121, 122, 123]])

In [21]:
print(t1 + t2)

[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]
 [124 126 128 130]
 [132 134 136 138]
 [140 142 144 146]]


In [22]:
t1 = np.arange(24).reshape((4, 6))
t2 = np.arange(0, 6)
print(t1)
print(t2)
print(t1 - t2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[0 1 2 3 4 5]
[[ 0  0  0  0  0  0]
 [ 6  6  6  6  6  6]
 [12 12 12 12 12 12]
 [18 18 18 18 18 18]]


### 7.向数组中添加元素

In [23]:
a_2 = np.array([[1, 2, 3], [4, 5, 6]])
a_2

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
print(np.append(a_2, [7, 8, 9]))  #没有指定行列，输出时会把二维变一维添加数组
print(np.append(a_2, [[7, 8, 9]], axis=0))  #指定在每一列末尾添加7，8，9
print(np.append(a_2, [[0, 0, 0], [7, 8, 9]], axis=1))  #在每一行末尾添加数组

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 0 0 0]
 [4 5 6 7 8 9]]


In [25]:
a = np.arange(1, 7).reshape(3, 2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
print(np.insert(a, 1, [7, 8, 9], axis=1))  #以列为单位，向索引之为1的列添加元素。

[[1 7 2]
 [3 8 4]
 [5 9 6]]


In [27]:
print(np.insert(a, 1, [4, 12], axis=0))  #以列为检索单位，往第2列插入4，12
x = np.mean(a, axis=0)  #求所有列的平均值
print(x)

[[ 1  2]
 [ 4 12]
 [ 3  4]
 [ 5  6]]
[3. 4.]


### 8、在数组中删除元素

In [28]:
a = np.arange(1, 10).reshape(3, 3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
print(np.delete(a, 0, axis=0))  #以行为单位，删除索引值为0的那一行
a

[[4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
print(np.delete(a, 5))  #删除索引为5的元素，没有指定行列默认展开数组

[1 2 3 4 5 7 8 9]


In [31]:
print(np.delete(a, 0, axis=1))  #以列为单位，删除索引值为0的哪一行
a

[[2 3]
 [5 6]
 [8 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 9、数组去重

In [32]:
import numpy as np

a = np.array([5, 2, 6, 2, 7, 5, 6, 8, 2, 9])

print('第一个数组：')
print(a)
print('\n')

print('第一个数组的去重值：')
u = np.unique(a)
print(u)
print('\n')

print('去重数组的索引数组：')
u, indices = np.unique(a, return_index=True)
print(indices)
print('\n')

print('我们可以看到每个和原数组下标对应的数值：')
print(a)
print('\n')

print('去重数组的下标：')
u, indices = np.unique(a, return_inverse=True)
print(u)
print('\n')

print('下标为：')
print(indices)
print('\n')

print('使用下标重构原数组：')
print(u[indices])
print('\n')

print('返回去重元素的重复数量：')
u, indices = np.unique(a, return_counts=True)
print(u)
print(indices)

第一个数组：
[5 2 6 2 7 5 6 8 2 9]


第一个数组的去重值：
[2 5 6 7 8 9]


去重数组的索引数组：
[1 0 2 4 7 9]


我们可以看到每个和原数组下标对应的数值：
[5 2 6 2 7 5 6 8 2 9]


去重数组的下标：
[2 5 6 7 8 9]


下标为：
[1 0 2 0 3 1 2 4 0 5]


使用下标重构原数组：
[5 2 6 2 7 5 6 8 2 9]


返回去重元素的重复数量：
[2 5 6 7 8 9]
[3 2 2 1 1 1]


## 数组拼接

In [36]:
a = [[1, 2], [3, 4]]
b = [[5, 6], [7, 8]]
a = np.array(a)
b = np.array(b)
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [40]:
#水平拼接
print(np.concatenate((a, b), axis=1))
#垂直凭借
print(np.concatenate((a, b), axis=0))

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### 堆叠

In [43]:
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [47]:
#水平堆叠，要注意的是堆叠的元素，行数必须相同
print(np.hstack((a,b)))
#纵向堆叠，两个数组必须列数相同
print(np.vstack((a,b) ))

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [48]:
a_1 = np.arange(24).reshape(4,6)
a_1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

## 分割

In [51]:
#以列为单位，把6列平均分成3份
print(np.hsplit(a_1,3))

[array([[ 0,  1],
       [ 6,  7],
       [12, 13],
       [18, 19]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21]]), array([[ 4,  5],
       [10, 11],
       [16, 17],
       [22, 23]])]


In [52]:
print(np.vsplit(a_1,4))

[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]]), array([[18, 19, 20, 21, 22, 23]])]


## 转置

In [58]:
print(a_1)
print(np.transpose(a_1))
a_1.T

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

In [62]:
a_2 = np.reshape(a_1,[2,3,4])
print(a_2)
a_2.T

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])