# 创建数组

In [29]:
import numpy as np
list1 = [1,2,3,4]
print(type(list1))
shuzu = np.array(list1)
print(type(shuzu))

<class 'list'>
<class 'numpy.ndarray'>


In [30]:
import numpy as np
list1 = [[5,9],[3,8],[7,6]]
twefvr= np.array(list1)
print(twefvr)
'''
[[5 9]
 [3 8]
 [7 6]]
'''

[[5 9]
 [3 8]
 [7 6]]


'\n[[5 9]\n [3 8]\n [7 6]]\n'

In [31]:
a = np.arange(1,25).reshape(4,6)
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [32]:
four = np.array([[1,2,3],[4,5,6]])
# 修改的是原有的
four.shape= (3,2)
print(four)

[[1 2]
 [3 4]
 [5 6]]


In [33]:
qwe = four.reshape(2,3)
print(qwe)

[[1 2 3]
 [4 5 6]]


In [34]:
print(four)
five = four.reshape((6,),order='F')
six = four.flatten(order='C')
print(five)
print(six)

[[1 2]
 [3 4]
 [5 6]]
[1 3 5 2 4 6]
[1 2 3 4 5 6]


In [38]:
t = np.arange(24)
print(t)
print(t.shape)
t1 = t.reshape((3,8))
print(t1)
print(t1.shape)
t2 = t.reshape((2,3,4))
print(t2)
print(t2.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
(3, 8)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
